### ISSUE TITLE
form layout : doc bug on horizontal alignement 

### ISSUE THREAD

**Issue by elvisbegovic** [salesforce-ux/design-system#586] opened 2018-10-09 08:49 UTC
Is this by design or legend should take whole width? 
![image](https://user-images.githubusercontent.com/2789203/46657587-e4e9a480-cbb0-11e8-9078-66697e5aa200.png)

link : https://www.lightningdesignsystem.com/components/form-element/#Horizontal-Alignment-2

**Comment by engai** [comment] 2018-10-09 17:59
Hi @istiti, this is by design with this version of forms. Since we want a max-width set on form element labels in the horizontal variant, the property is being applied to the element you've highlighted above. We understand that this also affects stacked form-elements within a horizontal form, and are working to make improvements.

With 2.8.0, we're making changes that will give users more control of their forms at the element level. This will help prevent a few inconsistencies moving forward.

**Comment by istiti** [comment] 2018-10-11 06:51
Ok,
In our case we have lot of inputs displayed at same time on the screen, not considering "horizontal form" will be annoying : scroll to fill/see all inputs. We can't use stacked form!
And actually I think stacked form are better more stable thant horizontal.  Near mobile screen, we have "Widescreen displays" we should consider more horizontal forms in SLDS.

@engai  thanks

**Comment by kflournoy-sf** [comment] 2021-01-25 18:48
Closing as this is no longer an issue due to updates since then.

**Closed by kflournoy-sf** 2021-01-25 18:48 UTC
Labels: roadmap
