### ISSUE TITLE
SVG Icons Not Showing Up in SF1 Lightning Tab

### ISSUE THREAD

**Issue by VinyWenkz** [salesforce-ux/design-system#219] opened 2016-05-17 04:11 UTC
I followed https://developer.salesforce.com/trailhead/project/slds-lightning-components-workshop/slds-lc-4.

The icons show up in the Developer Edition, but not in Sandbox. 
I copy+pasted the code to verify if it is a code issue, but still, nothing is showing up on Sandbox.

However, the space for the icon is noticeable.

**Comment by FabienTaillon** [comment] 2016-05-17 07:53
@VinyWenkz Is your Sandbox on Spring '16 or Summer '16 ? It seems there are some issues with SVG icons in Summer '16 with Locker Service activated currently.

**Comment by kaelig** [comment] 2016-05-17 17:10
Hi @VinyWenkz, thank you for bringing this to our attention!

Please follow up and watch #217 for updates, thank you.

Closing this, as it is a duplicate of #217.

**Closed by kaelig** 2016-05-17 17:10 UTC
