### ISSUE TITLE
iPad/iPhone - Default Scrollbar issue

### ISSUE THREAD

**Issue by CinoGeorge** [salesforce-ux/design-system#81] opened 2015-11-02 08:28 UTC
The default scroll bar for an outputText inside Lightning Component is not working, especially for iPad and iPhone. The default scroll bar is coming but when one try to scroll it the whole page is getting scrolled instead of the outputText wrapper. Screenshot of the page with default scrollbar is attached below. 

![image_screenshot1](https://cloud.githubusercontent.com/assets/15605990/10881472/f881fe9a-8188-11e5-9c7f-fe2f7f1e7c20.jpg)

The class 'slds-scrollable--y' for getting the default scroll bar is given for outputText. HTML code for the outputText is shown below:
```
<div class="slds-col slds-size--1-of-1 noteBox">
        <ui:outputText value="{!v.quarterlyForecastView.quarterlyForecastObject.scfcst__Notes__c}" aura:id="viewModeScrollBarY" class="slds-scrollable--y"/>
 </div>
```
Can you please provide a solution? Thanks in advance.

**Comment by richiechik** [comment] 2015-11-02 11:32
I'm having the exact same issue trying to make quick find pick list options or search box options scrollable in Salesforce1 App. Anyone know how to fix this please? I'm still on v.9.0 by the way...

**Comment by richiechik** [comment] 2015-11-11 22:55
Hi there, 

Is there any update on this bug please? I urgently need this fixed for our product release this month...

And I can't use the latest version just yet because the QuickFind Picklist is taken off. Could someone please share how could I fix this issue in v.9.0 please?

**Comment by kaelig** [comment] 2015-11-12 17:54
@richiechik thank you for your patience. We're investigating this bug right now and will keep you updated on a fix.

**Comment by kaelig** [comment] 2015-11-12 22:16
@CinoGeorge @richiechik have you tried scrolling with two fingers? This is how scrolling inside divs work on iOS.

In the mean time, please apply this property to the affected blocks:

```css
-webkit-overflow-scrolling: touch;
```

It will have for effect to provide momentum scrolling to the scrollable zones. The size effect (we're going to discuss if it's desirable or not) is that the zones won't show a scrollbar anymore.

**Comment by topherauyeung** [comment] 2015-11-12 22:44
@richiechik is this the Picklist you're looking for? https://www.lightningdesignsystem.com/components/menus#picklist

There was some navigational reorganization, and we moved the Picklist component to be a variant of the Menu component.

**Comment by richiechik** [comment] 2015-11-13 03:55
@topherauyeung Nope, its the Quick Find picklist that has been recently taken off I have been working on. I have got all the animations, search actions built in as a Lightning Component but the scrolling just not working in Salesforce1 Mobile app in ipad or iphone. Its working perfectly fine under the Lightning App on desktop through... 

I have tried the following in css but still with no luck...
`-webkit-overflow-scrolling: touch;`

**Comment by kaelig** [comment] 2015-11-13 18:06
@richiechik sorry to hear that, in our tests it seemed to solve the problem.

Can you share a reduced test case (in codepen or another tool like that) that we can reproduce the bug and investigate?

If that's too complicated, we can also meet. Please get in touch at kdeloumeau@salesforce.com and we'll arrange that.

**Comment by stefsullrew** [comment] 2015-11-13 20:55
@richiechik - the Quick Find picklist is still in the codebase if you clone the open source project. (Components > Picklist > Quick FInd) You could reenable it yourself if needed.

We've temporarily removed it because it has accessibility flaws that we need to fix. But it will be back.

**Comment by richiechik** [comment] 2015-11-16 00:32
@kaelig Thanks, I might need to email your guys because the code base is Salesforce Lightning components so I'm not sure if it will render in Codepen. 

@stefsullrew Is there any quick tutorial on how to compile these into css files please? I haven't learnt things like jsx and react yet...

**Comment by richiechik** [comment] 2015-11-18 02:24
@stefsullrew Could I get some help on how to re-enable QuickFind picklist and re-compile as css please?

**Comment by kaelig** [comment] 2015-11-18 20:26
@richiechik you can also download an old pre-compiled version of the Lightning Design System [in the "releases" page](https://github.com/salesforce-ux/design-system/releases) of the project and take out the CSS that's useful to you.

**Comment by CinoGeorge** [comment] 2015-11-19 12:45
@kaelig Sorry for the late reply. I tried to scroll with two fingers but still the scroll bar is not working. I have added the CSS mentioned above. The default scroll bar is not working even for android devices. The default scroll bar for text area is also not working in SalesForce1. Is that because of that pull to refresh option in Salesforce1 ?

**Comment by kaelig** [comment] 2015-11-20 19:49
Thank you all for your comments. I'm investigating this bug that only happens in our in-app webview. I'll let you know as soon as I find a fix.

**Comment by richiechik** [comment] 2015-11-23 06:23
@kaelig I just tried v.11.0 but I got the same results as @CinoGeorge that it doesn't work in the in-app browser... Thanks heaps.

**Comment by kaelig** [comment] 2015-11-23 18:37
Thank you, I've investigated and it is an issue related to the Salesforce1 app. I'm in touch with the developers. Feel free to get in touch with them as well to investigate nested scrolling issues.

Closing because this isn't related to the lightning design system but I'll follow up in this thread.

**Closed by kaelig** 2015-11-23 18:37 UTC
Labels: bug

**Comment by kaelig** [comment] 2015-11-23 20:23
Dear all, I've talked to the mobile team and it looks like for now the only way to build scrollable areas nested in the app is to use `ui:scroller`. Here is their answer:

> Unfortunately for the time being the only workaround is use the ui:scroller

Let me know how that works out for you.

**Comment by CinoGeorge** [comment] 2015-11-24 06:54
@kaelig Is ui:scroller a component? Can you please provide a code sample using ui:scroller.

**Comment by kaelig** [comment] 2015-11-24 19:19
In #84, @bearman17 says:
> Salesforce has created a "Known Issue" for this problem. Please click the "This Issue Affects Me" button if you're interested:
> https://success.salesforce.com/issues_view?id=a1p30000000ePVNAA2

@CinoGeorge unfortunately we do not provide support for components outside the design system on this GitHub repository at the moment. Please file an issue using the usual channels for Aura / Lightning components.

**Comment by aravindxz** [comment] 2016-12-13 09:16
The ui:scroller still has problem. I'm unable to scroll upwards once I scroll down. (I've used ui:scroller to enable scrolling in datatable in Salesforce1 app.)

**Comment by stefsullrew** [comment] 2016-12-13 21:32
I will pass this info on to the team that build ui:scroller (that's not the Design System team). Cheers!

**Comment by angelorendon** [comment] 2017-02-06 21:36
hi @aravindxz, did you ever find a work around for this ui:scroller in datatable in Salesforce? I have that exact issue and am trying everything to allow scrolling for it

**Comment by aravindxz** [comment] 2017-02-07 12:27
Hi @angelorendon  
Yes, but as mentioned in the previous reply, there's still issue in scroll when you want to have a fixed header for the  datatable in Salesforce1 app (For Lightning Desktop, everything is fine). And, if you do not want fixed header for the datatable in Salesforce1 app too, then the scroll works fine.

**Comment by stefsullrew** [comment] 2017-02-08 00:50
Hi all, it appears there's a newer component you should wrap your scrolling component in — ui:scrollerWrapper (as @aravindxz mentioned). Can you test to see if that fixes your problem @angelorendon?

I will pass the info about the fixed header along.
