### ISSUE TITLE
Stencils

### ISSUE THREAD

**Issue by rahulpatidar** [salesforce-ux/design-system#146] opened 2016-01-13 12:32 UTC
How to use Stencils in lightning experience salesforce

![stencils](https://cloud.githubusercontent.com/assets/6771587/12294366/da76746a-ba1f-11e5-9916-d2567770518a.PNG)

**Comment by kaelig** [comment] 2016-01-15 19:07
Thank you for asking, @rahulpatidar.

Before we come back to an answer, allow me to clarify that this refers to loading stencils. https://www.lightningdesignsystem.com/design/loading

> Stencils are placeholders that visually communicate that content is in the process of loading.

**Comment by kaelig** [comment] 2016-04-06 18:55
Closing this as it's a duplicate of #193

**Closed by kaelig** 2016-04-06 18:55 UTC
Labels: feature-request, question
