### ISSUE TITLE
Responsive classes are missing their counterpart

### ISSUE THREAD

**Issue by rsukale** [salesforce-ux/design-system#292] opened 2016-08-08 18:10 UTC
Here's what I want to do

```html
<div>
  <div class="slds-medium-show">Desktop Content(to be visible above> 768 px)</div>
  <div class="slds-medium-hide">Mobile/Tablet content(to be visible between 320px - 768px)</div>
</div>
```

However, there is no such class as "slds-medium-hide". Or counterparts for similar "show" classes.

**Comment by kaelig** [comment] 2016-08-08 18:53
Hi @rsukale, thank you for using the Lightning Design System!

You are correct, at the moment this is not doable with the provided visibility utility class names.

Let me label this as a Feature Request, so we can look into it in the future.

In the mean time, feel free to share any workarounds that you may have found!

**Comment by kaelig** [comment] 2016-08-09 18:47
Marking this as a duplicate of #263

**Closed by kaelig** 2016-08-09 18:47 UTC
Labels: duplicate, feature-request
