### ISSUE TITLE
Tabs refactored not reflected in all documentation

### ISSUE THREAD

**Issue by FabienTaillon** [salesforce-ux/design-system#107] opened 2015-11-20 10:50 UTC
Tabs has been refactored, however the documentation still refers to *.slds-tabs__item* or *.slds-tabs__content*, like in the *Javacript needs* or *Component Overview* (last 3 lines) sections.

Also, it's said that "Each tab panel has an aria-labelledby attribute whose value is the id of its associated \<a role="tab">". In the sample HTML, there is no *aria-labelledby* on the tabpanel, and no *id* on the associated *\<a role="tab">*.
On the other side, there is an *id* on the *role="tabpanel"* and an *aria-controls* attribute on the *role="tab"*, but they are not documented. It seems they have the same value, so I guess it's on purpose.

So:
* Is *aria-labelledby* still needed ?
* How do we know the link between the tab and the tabpanel ? 
    * Through *aria-labelledby* and the *id* of its associated *\<a role="tab">* ? 
    * Though *aria-controls* attribute and the *id* on the  *role="tabpanel"* ?

Thanks.

**Comment by kaelig** [comment] 2015-11-20 19:40
Salut Fabien, merci pour le retour, tu as l'œil ! (et un grand merci pour ton récent article sur le sujet)

@stefsullrew did some great refactoring work on this component, so I'll let her take it from here.

**Comment by stefsullrew** [comment] 2015-11-23 19:24
Interesting. This seems to be a regression. If you look at the tabs within our own site, they're actually using the `aria-labelledby` attribute. But it's missing on the component. I've got to take a deeper look at this.

Meanwhile, here's a good article on a11y and tab sets @FabienTaillon - https://www.marcozehe.de/2013/02/02/advanced-aria-tip-1-tabs-in-web-apps/

**Comment by kaelig** [comment] 2015-11-23 20:21
> Meanwhile, here's a good article on a11y and tab sets @FabienTaillon - https://www.marcozehe.de/2013/02/02/advanced-aria-tip-1-tabs-in-web-apps/

Yep, he's the one who opened the issue :p

**Comment by stefsullrew** [comment] 2015-11-23 20:23
Hi @FabienTaillon, meet Fabien! Wow. I'm laughing my butt off here. At least you know you wrote a good article, right?

**Comment by FabienTaillon** [comment] 2015-11-23 22:44
Haha that's ok @stefsullrew because I did wrote a blog post but it's not this one :P 
Mine is here, and talking about Lightning Design System directly:
http://www.fabientaillon.com/using-tabs-component-with-salesforce-lightning-design-system
It's while trying to update it that I found this issue.

I do have a new nice article to read though, so thanks ! :D

**Comment by stefsullrew** [comment] 2015-12-09 00:35
This fix will be in the next release. Thanks again.

**Closed by stefsullrew** 2015-12-09 00:35 UTC
Labels: bug
