### ISSUE TITLE
Color Inconsistencies between SLDS and Swatch Download

### ISSUE THREAD

**Issue by aaurrichio** [salesforce-ux/design-system#151] opened 2016-01-26 18:28 UTC
Wondering why colors listed in the Color section of LDS are not reflected accurately in the CLR(iOS) swatches. 

For example, the hex value for "brand color" listed in the Color section reads #0070D2, however the corresponding swatch has a hex value of #0A58C7.

**Comment by kaelig** [comment] 2016-01-26 20:27
Hi @aaurrichio, thank you for using the Salesforce Lightning Design System and for this very useful feedback.

We are investigating and will get back to you shortly. Thank you for your patience.

**Comment by kaelig** [comment] 2016-01-26 20:29
Closing this so we can take it to the project where tokens are stored: https://github.com/salesforce-ux/design-tokens/issues/2

**Comment by kaelig** [comment] 2016-01-27 22:11
Reopening! :)

**Comment by DrBoolean** [comment] 2016-01-28 18:59
Hi @aaurrichio 

Just want to let you know I'm looking into this. We haven't yet automated the swatch build so it has to be run manually and deployed with the next release. I believe the issue is simply that the swatch is out of date.

This is something we'll automate soon and I appreciate you brining to our attention - it helps in bumping the dev work priority.

**Comment by aaurrichio** [comment] 2016-01-28 19:01
Wonderful! Glad to help out and happy to know it will be accounted for.

**Comment by DrBoolean** [comment] 2016-06-16 18:32
@aaurrichio Just chiming in. It turns out there is a bug where xcode is just finding the "closest match". It's hard to control since CLR is closed source. We might have a alternate solution coming soon though! Hang tight and I appreciate you pointing this out so we could find this bug.

**Comment by kaelig** [comment] 2017-01-27 22:22
Closing this as it hasn't been updated for a year. Feel free to reopen if you feel strongly should be prioritized!

**Closed by kaelig** 2017-01-27 22:22 UTC
Labels: bug
