### ISSUE TITLE
slds-scrollable--y not working on Salesforce1 App #Bug

### ISSUE THREAD

**Issue by richiechik** [salesforce-ux/design-system#95] opened 2015-11-12 02:01 UTC
Hi there,

Can I please request for urgent help on the slds-scrollable--y styling. Users can not scroll up or down from any DIV or Dropdown list added with this class within Salesforce1 App in mobile devices (ie: iphone, ipad).

Is there any chance this could get fixed soon? I have tried many css tricks but I'm not expert on css on touch devices so any advice would be great.

Thanks!

**Comment by kaelig** [comment] 2015-11-12 17:52
Duplicate of #81

**Closed by kaelig** 2015-11-12 17:52 UTC
