### ISSUE TITLE
Stencil example codes (component request)

### ISSUE THREAD

**Issue by mshanemc** [salesforce-ux/design-system#193] opened 2016-04-06 18:43 UTC
Can we (Salesforce) make some stencil examples available for some of our components?

For example, having list views, detail, buttons, tabs, cards/tiles, process paths, etc would be helpful.  

Otherwise, you're going to have a whole bunch of people trying to follow our design guide but writing their own stencil stuff.

---

Note from Kaelig: "Stencils" are loading patterns, see https://www.lightningdesignsystem.com/design/loading

**Comment by kaelig** [comment] 2016-04-06 18:46
Hi @mshanemc, can you get back in touch with us through the internal channels (Lightning Design System group on chatter)? You'll have more visibility and our product owner can prioritize this feature request better.

Thank you so much!

Closing this as it's a duplicate of https://github.com/salesforce-ux/design-system/issues/146

**Comment by mshanemc** [comment] 2016-04-06 18:52
I did, but was sent here by Stephanie because I lack GUS.

**Comment by kaelig** [comment] 2016-04-06 18:53
Oh, my bad! I thought all Salesforce employees had access to our internal Chatter.

**Comment by kaelig** [comment] 2016-04-06 18:54
Actually let's keep your issue as the master feature request and close the old one, as yours makes a more compelling case for it.

**Comment by interactivellama** [comment] 2016-04-07 20:49
Please make this something importable from npm modules for those working on SLDS Javascript controls and **not just cut-and-paste examples on the document site**.

**Comment by aravindxz** [comment] 2016-06-02 10:26
@kaelig @mshanemc Are there any examples showing use of stencils? If so, it would be really grateful if you could post the link or some sort of an example to show the same.

**Comment by mshanemc** [comment] 2016-06-06 18:37
like the bottom of this page: https://www.lightningdesignsystem.com/design/loading/

**Comment by aravindxz** [comment] 2016-06-07 01:17
@mshanemc So, you're saying that stencils are not a particular feature of SLDS?! You've to create another design specifically and then render it if the page load time is greater than 300ms?
And Shane, I wouldn't have specifically asked for an example if the information provided in the link which you just posted above was complete with a working example.
Please find a question related to the same below
[](http://salesforce.stackexchange.com/questions/111425/lightning-show-stencil-when-component-loads#)

**Comment by srohde** [comment] 2016-06-07 03:17
We are thinking about adding stencils to SLDS in the future.
I don't have a timeline for that yet but it's on the radar.

**Comment by aravindxz** [comment] 2016-06-07 04:27
Thanks for the clarification @srohde .

**Comment by up2go-sschwarz** [comment] 2018-03-20 11:49
@srohde it's about two year ago now, any road map updates about stencils?

**Comment by istiti** [comment] 2018-03-20 13:21
please apologize to make noise here, its not negative critics  but can salesforce team avoid  have "everything" in their roadmap ? because it seems to me for all feat. request response is "on our road map"

Can we imagine something like short list road map and others roadmap and set date aproximativly for tentative release, to invoke only one even big projet like typescript have it https://github.com/Microsoft/TypeScript/wiki/Roadmap 

I think be closest to users should be mandatory. what community think ?

thanks for awesome designers at salesforce

cc @srohde  @engai

**Comment by engai** [comment] 2018-04-10 19:54
Hey @istiti, thank you for your suggestion. We discussed a "roadmap" feature as a team last week and agree that it would be a great idea.

We'll be sure to let you know when that is released or if we run into any complications with making it publicly available.

**Comment by engai** [comment] 2018-04-10 19:55
As far as stencils...

@stefsullrew @aweibel any thoughts on surfacing these?

**Comment by interactivellama** [comment] 2018-04-10 20:47
👍  [Design System React](https://github.com/salesforce/design-system-react) would love pulling in stencils. Stencils tend to need to scale (5 rows? 10 rows?) and be customizable for each app they are in--which can be tricky.

I'd suggest another tab in the website, "Loading state" or something.

**Comment by stefsullrew** [comment] 2018-04-28 00:46
@engai Stencils are not built through the Design System. While we'd love to get to them, we've had some pretty big projects lately, so they have continued to fall below the line.

That said, we're gonna publish you a roadmap! We can't promise when things will get done, but we can at least give you a basic priority order...

**Comment by istiti** [comment] 2018-10-28 12:04
.

**Comment by moshner** [comment] 2018-11-05 18:41
I would also love to see stencils available in the LDS. We're implementing the LDS internally and using the static assets.

**Comment by marceloatg** [comment] 2019-03-05 19:33
Common stale bot bot, give the team some time to figure this one out, because stencils will help a lot to deliver that amazing lightning look and feel consistently!

**Comment by e02d96ec16** [comment] 2019-07-04 08:40
![image](https://user-images.githubusercontent.com/14942417/60652208-b34ff200-9e3f-11e9-88f6-1b1a53650427.png)

**Comment by FabienTaillon** [comment] 2020-02-03 12:46
I'm also wishing to have this.
Styles already exists on the platform, I'm able to use them and create a working stencil.
However as they are not documented, they could potentially break at any time.

![stencils](https://user-images.githubusercontent.com/2465122/73654235-72e17c80-468b-11ea-9454-c31807952323.png)

**Comment by FabienTaillon** [comment] 2020-06-02 15:04
The issue wouldn't be stale if someone from Salesforce could take the time to answer. Last answer is 2 years old.

**Comment by stefsullrew** [comment] 2020-06-04 02:44
I know @FabienTaillon ... I know. (Hello again!) The issue is that we (SLDS) don't own these. And until we take ownership (and there have been higher priorities), we won't be able to provide them externally. That said, you might be pleased to know that this has internally been raised again recently. So maybe your wish will come true?

**Comment by FabienTaillon** [comment] 2020-06-05 07:08
That would be cool ! 🤞

**Comment by moshner** [comment] 2020-10-04 15:48
Bump

**Comment by Ihor-Horchynskyi** [comment] 2020-12-22 14:44
Bump

**Comment by forcetrekker** [comment] 2021-04-13 13:30
Just checking, any updates. :)

**Comment by moshner** [comment] 2021-04-13 14:27
"Otherwise, you're going to have a whole bunch of people trying to follow our design guide but writing their own stencil stuff."

FYI, I've already developed a library of the SLDS components that we use the most. I can talk to my company about open-sourcing it. If enough people think they would be interested in helping maintain them I think we might get more traction.

**Comment by forcetrekker** [comment] 2022-01-09 00:31
Just checking if is there any thought on this ticket

**Comment by aneeshack4** [comment] 2022-01-19 23:47
We have explored this. The way our platform is built, stencils cannot come from SLDS so we will not be providing stencil example codes or blueprints as of now.

**Closed** 2022-01-19 23:48 UTC
Labels: feature-request

**Comment by stefsullrew** [comment] 2022-01-20 00:05
I should add for folks that are external, Aneesha Kommineni (who's note you see above) is our product manager. Sorry we couldn't work this out for y'all.
