### ISSUE TITLE
Easy theming using Sass variables

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#369] opened 2016-12-17 23:48 UTC
Enhancement: actually in scss folder to change primary color or secondary we have a lot of color variable , we can't easy change look and feel of the app! The difference with material design by example is that we define 4 main colors primary secondary lighter darker that's all! and others generated automatically with opacity ! 

What do you think about, how you achieve this requirement ?

**Comment by kaelig** [comment] 2016-12-19 04:57
Thank you for your question, @istiti. We're looking into it at the moment and can't announce anything yet, but watch this space!

**Comment by kaelig** [comment] 2017-01-27 22:07
Duplicate of #185

**Closed by kaelig** 2017-01-27 22:07 UTC
Labels: duplicate, feature-request
