### ISSUE TITLE
Notifications - animation classes

### ISSUE THREAD

**Issue by seanrussell** [salesforce-ux/design-system#144] opened 2016-01-12 17:21 UTC
The documentation for notifications mentions that toast components take duration and dismissable parameters. What are these parameters referring to? I thought that maybe there were variables in the SCSS that can be used to generate certain classes like slds-alert--slow-duration or slds--fast-duration, but I don't see anything like that in the source code.  Maybe I'm missing something?

**Comment by kaelig** [comment] 2017-01-27 21:58
Duplicate of #296

**Closed by kaelig** 2017-01-27 21:58 UTC
Labels: feature-request
