### ISSUE TITLE
SVG is not rerendering..

### ISSUE THREAD

**Issue by Karekallu** [salesforce-ux/design-system#264] opened 2016-07-02 11:11 UTC
```xml
<apex:form id="sortRender">
    <apex:selectList value="{!countries}" size="1">
        <apex:selectOptions value="{!ListSortByTasks}" />
        <apex:actionSupport action="{!sortOption}" event="onchange" rerender="sortRender,out,mypael,repeatID,dtable,div1,div2,div3,div4" status="myStatus" />
    </apex:selectList>
    <apex:outputPanel id="out">
        <apex:actionStatus startText="requesting..." stopText=" (done)" id="myStatus">
        </apex:actionStatus>
    </apex:outputPanel>
    <apex:outputPanel id="mypael">
        <apex:datatable value="{!accountData}" var="acc" id="dtable">
            <apex:column>
                <div class="slds-card slds-card--narrow">
                    <div class="slds-card__header slds-grid" id="div2">
                        <div class="slds-media slds-media--center slds-has-flexi-truncate" id="div3">
                            <apex:outputPanel>
                                <div class="slds-media__figure">
                                    <svg aria-hidden="true" class="slds-icon slds-icon-standard-contact slds-icon--medium">
                                        <use xlink:href="{!URLFOR($Resource.SLDS104,'assets/icons/standard-sprite/svg/symbols.svg#contact')}"></use>
                                    </svg>
                                </div>
                            </apex:outputPanel>

                            <span class="slds-text-heading--small">{!acc.name}</span>
                            <div class="slds-media__body ">
                                <span class="slds-text-heading--small">{!acc.name}</span>
                                <div class="slds-tile__detail slds-text-body--small">
                                    <dl class="slds-dl--horizontal">
                                        <dd class="slds-dl--horizontal__detail slds-tile__meta">
                                            <p class="slds-truncate" title="Visit">Login # last 30 days: {!acc.DOB__c}</p>
                                        </dd>
                                        <dd class="slds-dl--horizontal__detail slds-tile__meta">
                                            <p class="slds-truncate" title="1/31/15 3:45PM">last login: {!acc.Country__c}</p>
                                        </dd>
                                    </dl>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

</form>
```

**Comment by kaelig** [comment] 2016-07-05 18:33
Closing this as it's a duplicate of #265

**Closed by kaelig** 2016-07-05 18:33 UTC
Labels: bug, duplicate
