### ISSUE TITLE
SLDS minified css file inconsistent between managed and unmanaged packages.

### ISSUE THREAD

**Issue by suryatej16** [salesforce-ux/design-system#342] opened 2016-10-27 17:10 UTC
I am using the minified 2.1.3 version of the SLDS css file in a package I am working on. I am noticing inconsistencies, mainly with the calc() function, in the css file between my dev org and when I create a managed package. Here is one example, the Process bar:

If you notice below, the arrows between the steps are properly rendered, with the CSS as follows:
`.slds-tabs--path__item:before{content:'';display:block;position:absolute;top:2px;left:-1rem;width:calc(2rem - (2px * 2));height:calc(2rem - (2px * 2));`

Notice the spacing between the items in the calc() function.

![correctlyrendered](https://cloud.githubusercontent.com/assets/5589728/19777331/8e16d0f2-9c2c-11e6-98cc-a2ce1d3aad3c.png)

This is when I create a managed package from my code. Notice the arrows are not rendered here, and the css for this is as follows:
`.slds-tabs--path__item:before{content:'';display:block;position:absolute;top:2px;left:-1rem;width:calc(2rem -(2px * 2));height:calc(2rem -(2px * 2));`

Notice that the spacing in the calc() function is now different, the minus sign and the parenthetical expression no longer have a space between them.

![incorrectlyrendered](https://cloud.githubusercontent.com/assets/5589728/19777348/acbdea90-9c2c-11e6-8b4e-19468582afbb.png)

Has anyone encountered inconsistencies like these before? I understand this might not be the proper forum for this question, and if not, could someone direct me to a better place?

**Comment by kaelig** [comment] 2016-10-27 23:16
Good catch, @suryatej16! Thank you for sharing and asking.

I'll need to know how you got the CSS that's in your managed package. Where did you download/compile it from?

**Comment by suryatej16** [comment] 2016-10-27 23:56
I downloaded it from the following link: https://www.lightningdesignsystem.com/downloads/

The problem isn't in the file that is downloaded. That file is correctly formatted. It's only when the CSS gets uploaded as part of a managed package that the CSS formatting changes.

**Comment by kaelig** [comment] 2016-10-31 18:38
Thanks @suryatej16.

I've tried to reproduce the issue and unfortunately couldn't.

Could you please describe the steps necessary to reproduce the issue and what are the pre-requisites (type of org, access rights…)?

**Comment by stefsullrew** [comment] 2016-11-29 18:36
@suryatej16 - is this happening with a managed package in VF or on the platform?

**Comment by suryatej16** [comment] 2016-11-30 19:37
This is happening with a managed package in VF. The steps to reproduce would be to create a VF page in a sample managed package and use the Sales Path navigation component on the page.

**Comment by kaelig** [comment] 2016-11-30 22:15
Thanks, I tried what you describe (at least I think this is what you described), and couldn't reproduce it.

**Comment by kaelig** [comment] 2016-12-09 00:00
@suryatej16 would you mind describing the steps as closely as possible to what you've done so we can try to repeat the issue?

**Comment by kaelig** [comment] 2017-01-25 19:12
Closing this as we couldn't reproduce the issue.

**Closed by kaelig** 2017-01-25 19:12 UTC
Labels: bug
