### ISSUE TITLE
Strike Multiselect options should overlap "slds-scrollable" modal

### ISSUE THREAD

**Issue by rsoesemann** [salesforce-ux/design-system#483] opened 2017-08-10 14:48 UTC
I am using a <c:strike_multiSelectPicklist> in a scrollable modal 

```
<div class="slds-modal__content slds-p-around_medium" id="modal-content-id-1">
	<div class="slds-scrollable">
        <ul class="slds-accordion">
            <aura:iteration items="{!v.attributes}" var="attribute">
                <c:strike_multiSelectPicklist label="Filter volumes by" value="{!attribute.filters}" onchange="{!c.changeFilters}" placeholder="{!attribute.label + ' - Select values'}">
                    <aura:iteration items="{!attribute.values}" var="value">
                        <c:strike_option label="{!value}" value="{!value}"/>
                    </aura:iteration>
                </c:strike_multiSelectPicklist>
            </aura:iteration>
        </ul>
    </div>
</div>
```

and I want the strike-options of the current focus to overlap the scrollable area to make them better visible. I have tried to add a overflow: visible basically everywhere but it doesn't work. 

<img width="683" alt="bildschirmfoto 2017-08-09 um 10 52 36" src="https://user-images.githubusercontent.com/8180281/29115407-dcff3d9c-7cf7-11e7-8117-a065e3cffe1c.png">

This looks like either a SLDS bug or a problem with Strike's implementation.

I don't want to edit the strike-options component but think you will need to apply the right CSS z-index property (or the right class) on the ui:scrollerWrapper component or below.

NOTE: I also added a StackExchange question for this: https://salesforce.stackexchange.com/questions/187964

**Comment by up2go-rsoesemann** [comment] 2017-08-18 08:48
Is this the wrong place to post my question or why is this "ignored"?

**Comment by engai** [comment] 2017-12-19 19:55
Hi @up2go-rsoesemann, our apologies for the delayed response. Were you able to fix your issue?

I'm not sure if this qualifies as a bug on our end since the components are behaving as expected. Since your lookup component is within a scrollable container, it is technically not overflowing out of the container itself.

**Comment by engai** [comment] 2018-04-09 23:52
@rsoesemann Any updates on this? Again, we believe that our components are behaving as designed since we wouldn't want elements overflowing outside of a modal body.

Closing this issue, but feel free to reopen or comment.

**Closed by engai** 2018-04-09 23:52 UTC
