### ISSUE TITLE
slds tree <li> overridden margin-left in css

### ISSUE THREAD

**Issue by matejp84** [salesforce-ux/design-system#176] opened 2016-03-22 09:35 UTC
There is margin-left set to 0 on: ".slds li" selector, so tree component is all stacked to left instead of being nicely indented in tree structure.

**Comment by stefsullrew** [comment] 2016-03-22 22:49
Hi @matejp84 - this is a duplicate of https://github.com/salesforce-ux/design-system/issues/164. It will be available in our next release.

**Closed by stefsullrew** 2016-03-22 22:49 UTC
Labels: duplicate, scoped-build
