### ISSUE TITLE
Rows in generic tile are misaligned if <p class="slds-truncate"> is empty

### ISSUE THREAD

**Issue by dancinllama** [salesforce-ux/design-system#51] opened 2015-10-14 19:59 UTC
I'm using several instances of the generic title outlined here: http://www.lightningdesignsystem.com/components/tiles in a lightning component.

One thing I've noticed is that if the &lt;p class="slds-truncate"&gt; tag is missing content (rather it is empty), then the next row is pushed up into its place, resulting in a mismatch between the label and the element.

The easy fix currently is to add a non-breaking space at the end of the values, but regardless there should be a less hacky way to handle empty p tags.

**Comment by kaelig** [comment] 2016-07-11 22:36
This seems to have been fixed in a recent release, as I couldn't reproduce this issue.

Feel free to re-open it if that's still an issue.

**Closed by kaelig** 2016-07-11 22:36 UTC
Labels: bug
