### ISSUE TITLE
Size attribute in lightning:icon only changes the width

### ISSUE THREAD

**Issue by chupchap** [salesforce-ux/design-system#362] opened 2016-12-09 17:27 UTC
The 'size' attribute in lightning:icon only changes the width of the icon and not the height.  This leads to the icons being skewed. The only work around as of now is to go back to using svg tag and linking to it.

The issue is visible when using sizes 'small', 'x-small', and 'xx-small'.

**Comment by kaelig** [comment] 2016-12-09 21:49
Thank you @chupchap for opening this issue, I'll mark this as a duplicate of #228.

**Comment by stefsullrew** [comment] 2016-12-12 04:47
I'm not sure this is a duplicate. xx-small is a size that was never meant to be used with the round avatars/icons. But that's not documented (nor is it a use case). So I"m interested in knowning more about small, x-small, etc...

**Comment by chupchap** [comment] 2016-12-13 04:52
Hi @stefsullrew I'm going by the [documentation](https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/aura_compref_lightning_icon.htm?search_text=lightning:icon) given in Lightning Component Developer guide. Over there I have an option to use various sizes. 

Two suggestions, please ask relevant team to mention in the developer guide which all icons (utility types only?) support different size. Secondly, please try to support all sizes for all icons in the future. I'm not at my system now and will post the DOM as soon as I'm in office.

**Comment by JohnHeadIV** [comment] 2016-12-13 05:07
we've had issues with lightning:icon utilization within communities so we've stuck with the custom svg component out of the documentation. Using the icon sizing classes doesn't seem to prevent as much issues. The issues I see with --x-small is that it does not adjust the line in the icon container (generally inheriting a height of 1) If the line height is adjust down to .875 then you get the circle. Setting it to always be .875 does not seem to have any impact on other sizes/shapes. We've update the custom svg component to include this alongside the default slds-icon_container.

**Comment by kaelig** [comment] 2017-01-27 22:08
Duplicate of #362. Closing this as it seems related to the same root problem.

**Closed by kaelig** 2017-01-27 22:08 UTC
Labels: bug, duplicate
