### ISSUE TITLE
success button styling not displaying w/ VF component

### ISSUE THREAD

**Issue by tylerzika** [salesforce-ux/design-system#409] opened 2017-02-28 19:20 UTC
When I use the Visualforce Component to load SLDS, the styling for the success button does not display on the page. All the other button styling appears to work.

```
 <apex:page>
    <apex:slds />
    
    <div class="slds-scope">
        <button class="slds-button slds-button--success">Success</button>                    
    </div>

</apex:page>
```

**Comment by FabienTaillon** [comment] 2017-03-01 09:47
@tylerzika I think it's because of this issue: https://github.com/salesforce-ux/design-system/issues/395.

`<apex:slds />` is still loading slds v2.1.3 which doesn't include `slds-button--success`.

**Comment by kaelig** [comment] 2017-03-02 19:40
Thank you for reporting this, we're doing our best to fix this as soon as possible.

Marking it as a duplicate of #395

**Closed by kaelig** 2017-03-02 19:40 UTC
Labels: bug, status:duplicate
