### ISSUE TITLE
Bad selector with tree aria level

### ISSUE THREAD

**Issue by ennoucas** [salesforce-ux/design-system#164] opened 2016-03-08 20:24 UTC
The 1.0.0 ltng css is provided with this selector: `[aria-level="1"] > .slds .slds-tree__item` instead of `[aria-level="1"] > .slds-tree__item` as specified in the documentation. (same issue for all area levels)

**Comment by stefsullrew** [comment] 2016-03-09 00:29
Hi @ennoucas - which version of the CSS did you find this in? Is it one of the scoped versions? And if so, can you let us know which one? 

Cheers

**Comment by ennoucas** [comment] 2016-03-09 14:06
It is the _salesforce-lightning-design-system-ltng_ and _salesforce-lightning-design-system-ltng.min_ version 1.0.0

**Comment by kaelig** [comment] 2016-03-10 21:19
Duplicate of #91

**Closed by kaelig** 2016-03-10 21:19 UTC
Labels: bug, duplicate, scoped-build

**Comment by kaelig** [comment] 2016-04-09 00:47
Thank you for your patience, this was just fixed in the latest version of the Lightning Design System!

See full release notes: https://www.lightningdesignsystem.com/release-notes/
