### ISSUE TITLE
Firefox Section Title Component align issue

### ISSUE THREAD

**Issue by snownoop** [salesforce-ux/design-system#372] opened 2017-01-05 13:56 UTC
In latest Firefox browser (v 50.1.0) in Section Title Component
https://www.lightningdesignsystem.com/components/utilities/text/#flavor-section-title-section-title-open

Icon and Text are not aligned (oneline) like on other browsers due to display: flex css property (as i think).

**Comment by kaelig** [comment] 2017-01-05 18:44
Thank you for reporting this.

Closing it as it is a duplicate of https://github.com/salesforce-ux/design-system/issues/343

**Closed by kaelig** 2017-01-05 18:45 UTC
