### ISSUE TITLE
Web Link loading Issue

### ISSUE THREAD

**Issue by GuptaPathi** [salesforce-ux/design-system#371] opened 2017-01-05 10:22 UTC
https://www.lightningdesignsystem.com/components/feeds/
This link was not loading properly.
Kindly check and update the issue.

Regards
P S Gupta

**Comment by kaelig** [comment] 2017-01-05 18:44
Thank you for reporting this, @GuptaPathi!

I'm afraid I couldn't reproduce the issue.

May I ask what operating system / browser you are using?

**Comment by kaelig** [comment] 2017-01-24 18:41
Closing this as I couldn't reproduce the issue.

**Closed by kaelig** 2017-01-24 18:41 UTC
