### ISSUE TITLE
Windows 10 installation requirements

### ISSUE THREAD

**Issue by jonathanarbely** [salesforce-ux/design-system#544] opened 2018-04-19 15:49 UTC
Before doing `npm install` on a Windows 10 machine, are there any other languages (e.g. Phython) or software modules that need to be installed globally (except for Node.js and NPM of course)?

I'm asking because the installation keeps failing for me. Tried installing with CMD opened as admin.

The installation ends with these lines:
```
66696 verbose pkgid node-sass@4.5.2
66697 verbose cwd C:\Users\Jonathan Arbely\MAGELLAN\GIT\dlsjflsjdf\design-system-2.5.2
66698 verbose Windows_NT 10.0.16299
66699 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Jonathan Arbely\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
66700 verbose node v9.11.1
66701 verbose npm  v5.6.0
66702 error code ELIFECYCLE
66703 error errno 1
66704 error node-sass@4.5.2 postinstall: `node scripts/build.js`
66704 error Exit status 1
66705 error Failed at the node-sass@4.5.2 postinstall script.
66705 error This is probably not a problem with npm. There is likely additional logging output above.
66706 verbose exit [ 1, true ]
```

**Comment by JamesSingleton** [comment] 2018-04-27 05:00
I would also like to know as I am on Windows 10 and my build fails as well

```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 4/26/2018 9:47:47 PM.
Project "E:\Coding\SandBox\style_guides\design-system\node_modules\node-sass\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Micr
osoft.NuGet.targets (186,61)" does not exist in the project, and will be ignored.
Project "E:\Coding\SandBox\style_guides\design-system\node_modules\node-sass\build\binding.sln" (1) is building "E:\Coding\SandBox\st
yle_guides\design-system\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) on node 1 (default targets).
Project "E:\Coding\SandBox\style_guides\design-system\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) is building "E:\Codi
ng\SandBox\style_guides\design-system\node_modules\node-sass\build\src\libsass.vcxproj" (3) on node 1 (default targets).
PrepareForBuild:
  Creating directory "Release\obj\libsass\".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKD
ir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. [E:\Coding\SandBox
\style_guides\design-system\node_modules\node-sass\build\src\libsass.vcxproj]
  Creating directory "E:\Coding\SandBox\style_guides\design-system\node_modules\node-sass\build\Release\".
  Creating directory "Release\obj\libsass\libsass.tlog\".
InitializeBuildStatus:
  Creating "Release\obj\libsass\libsass.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  CL.exe /c /I"C:\Users\James Singleton\.node-gyp\8.7.0\include\node" /I"C:\Users\James Singleton\.node-gyp\8.7.0\src" /I"C:\Users\Ja
  mes Singleton\.node-gyp\8.7.0\deps\uv\include" /I"C:\Users\James Singleton\.node-gyp\8.7.0\deps\v8\include" /I..\..\src\libsass\inc
  lude /Zi /nologo /W3 /WX- /Ox /Ob2 /Oi /Ot /Oy /GL /D NODE_GYP_MODULE_NAME=libsass /D USING_UV_SHARED=1 /D USING_V8_SHARED=1 /D V8_
  DEPRECATION_WARNINGS=1 /D WIN32 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _HAS_EXCEPTIONS=0 /D "LIBSASS_VERSION=\
  "3.5.0.beta.2\"" /GF /Gm- /MT /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR- /Fo"Release\obj\libsass\\" /Fd"Release\o
  bj\libsass\libsass.pdb" /Gd /TP /wd4267 /wd4351 /wd4355 /wd4800 /wd4251 /errorReport:queue /GR /EHsc /MP ..\..\src\libsass\src\ast.
  cpp ..\..\src\libsass\src\ast_fwd_decl.cpp ..\..\src\libsass\src\base64vlq.cpp ..\..\src\libsass\src\bind.cpp ..\..\src\libsass\src
  \check_nesting.cpp ..\..\src\libsass\src\color_maps.cpp ..\..\src\libsass\src\constants.cpp ..\..\src\libsass\src\context.cpp ..\..
  \src\libsass\src\cssize.cpp ..\..\src\libsass\src\emitter.cpp ..\..\src\libsass\src\environment.cpp ..\..\src\libsass\src\error_han
  dling.cpp ..\..\src\libsass\src\eval.cpp ..\..\src\libsass\src\expand.cpp ..\..\src\libsass\src\extend.cpp ..\..\src\libsass\src\fi
  le.cpp ..\..\src\libsass\src\functions.cpp ..\..\src\libsass\src\inspect.cpp ..\..\src\libsass\src\json.cpp ..\..\src\libsass\src\l
  exer.cpp ..\..\src\libsass\src\listize.cpp ..\..\src\libsass\src\memory\SharedPtr.cpp ..\..\src\libsass\src\node.cpp ..\..\src\libs
  ass\src\output.cpp ..\..\src\libsass\src\parser.cpp ..\..\src\libsass\src\plugins.cpp ..\..\src\libsass\src\position.cpp ..\..\src\
  libsass\src\prelexer.cpp ..\..\src\libsass\src\remove_placeholders.cpp ..\..\src\libsass\src\sass.cpp ..\..\src\libsass\src\sass2sc
  ss.cpp ..\..\src\libsass\src\sass_context.cpp ..\..\src\libsass\src\sass_functions.cpp ..\..\src\libsass\src\sass_util.cpp ..\..\sr
  c\libsass\src\sass_values.cpp ..\..\src\libsass\src\source_map.cpp ..\..\src\libsass\src\subset_map.cpp ..\..\src\libsass\src\to_c.
  cpp ..\..\src\libsass\src\to_value.cpp ..\..\src\libsass\src\units.cpp ..\..\src\libsass\src\utf8_string.cpp ..\..\src\libsass\src\
  util.cpp ..\..\src\libsass\src\values.cpp
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [E:\Coding\SandBox\style_guides\desig
n-system\node_modules\node-sass\build\src\libsass.vcxproj]


Done Building Project "E:\Coding\SandBox\style_guides\design-system\node_modules\node-sass\build\src\libsass.vcxproj" (default target
s) -- FAILED.

Done Building Project "E:\Coding\SandBox\style_guides\design-system\node_modules\node-sass\build\binding.vcxproj.metaproj" (default t
argets) -- FAILED.

Done Building Project "E:\Coding\SandBox\style_guides\design-system\node_modules\node-sass\build\binding.sln" (default targets) -- FA
ILED.


Build FAILED.

"E:\Coding\SandBox\style_guides\design-system\node_modules\node-sass\build\binding.sln" (default target) (1) ->
"E:\Coding\SandBox\style_guides\design-system\node_modules\node-sass\build\binding.vcxproj.metaproj" (default target) (2) ->
"E:\Coding\SandBox\style_guides\design-system\node_modules\node-sass\build\src\libsass.vcxproj" (default target) (3) ->
(PrepareForBuild target) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSD
KDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. [E:\Coding\SandB
ox\style_guides\design-system\node_modules\node-sass\build\src\libsass.vcxproj]


"E:\Coding\SandBox\style_guides\design-system\node_modules\node-sass\build\binding.sln" (default target) (1) ->
"E:\Coding\SandBox\style_guides\design-system\node_modules\node-sass\build\binding.vcxproj.metaproj" (default target) (2) ->
"E:\Coding\SandBox\style_guides\design-system\node_modules\node-sass\build\src\libsass.vcxproj" (default target) (3) ->
(ClCompile target) ->
  TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [E:\Coding\SandBox\style_guides\des
ign-system\node_modules\node-sass\build\src\libsass.vcxproj]

    1 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.16
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\Coding\SandBox\style_guides\design-system\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\Coding\\SandBox\\style_guides\\design-system\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\Coding\SandBox\style_guides\design-system\node_modules\node-sass
gyp ERR! node -v v8.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN react-test-renderer@16.2.0 requires a peer of react@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\James Singleton\AppData\Roaming\npm-cache\_logs\2018-04-27T04_47_49_422Z-debug.log
```

The above is what my `npm install` ends with. If I try to do `npm start` after that, I get this:

```
> design-system@2.5.2 start E:\Coding\SandBox\style_guides\design-system
> npm run build && npm run previewer


> design-system@2.5.2 build E:\Coding\SandBox\style_guides\design-system
> gulp build

Error: Cannot find module 'gulp-sass'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:/Coding/SandBox/style_guides/design-system/scripts/gulp/styles.js:11:14)
    at Module._compile (module.js:624:30)
    at loader (E:\Coding\SandBox\style_guides\design-system\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (E:\Coding\SandBox\style_guides\design-system\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\Coding\SandBox\style_guides\design-system\gulpfile.js:17:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! design-system@2.5.2 build: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the design-system@2.5.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\James Singleton\AppData\Roaming\npm-cache\_logs\2018-04-27T04_48_23_010Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! design-system@2.5.2 start: `npm run build && npm run previewer`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the design-system@2.5.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\James Singleton\AppData\Roaming\npm-cache\_logs\2018-04-27T04_48_23_027Z-debug.log
```

Node version: 8.7.0
npm version: 6.0.0

I did notice that at the beginning of `npm install` I get this line:

```
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.2/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.2/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.5.2 postinstall E:\Coding\SandBox\style_guides\design-system\node_modules\node-sass
> node scripts/build.js
```

And the URL indeed does 404

**Comment by engai** [comment] 2018-06-28 18:57
Hi @jonathanarbely @JamesSingleton, sorry to hear that you're experiencing issues on Windows 10. I recently ran an npm install and start on Windows 10 and couldn't reproduce your error on npm install Though, I was on node 8.11.2.

Beyond Node, you may need to globally install [windows-build-tools](https://www.npmjs.com/package/windows-build-tools) to bring in Python. If you run into further issues with `npm start`, see a possible solution in https://github.com/salesforce-ux/design-system/issues/562

**Comment by engai** [comment] 2018-07-18 20:19
Closing this issue, but feel free to comment and reopen if you're still experiencing issues.

**Closed by engai** 2018-07-18 20:19 UTC
Labels: windows
