### ISSUE TITLE
Lookup Component not easily viewable in Modal with Standard SLDS in LEX

### ISSUE THREAD

**Issue by ktevatt** [salesforce-ux/design-system#399] opened 2017-02-17 16:42 UTC
`div.listContent` displays beneath the modal footer. When viewing a modal that initially has no scrolling, the exposed lookup items cause the height to change, but the user is not immediately aware that scrolling is required. Suggested improvement would have the lookup container appear above the modal footer.
<img width="527" alt="new_area_of_interest_-_no_preview___salesforce" src="https://cloud.githubusercontent.com/assets/25848932/23074155/f98e3b22-f505-11e6-8074-f62d5acd65f0.png">

**Comment by FabienTaillon** [comment] 2017-02-17 16:46
I think it's a duplicate of this [one](https://github.com/salesforce-ux/design-system/issues/353), which conclusion was that it was the expected behavior.

**Comment by kaelig** [comment] 2017-02-17 18:51
Thank you for asking, @ktevatt.

And merci @FabienTaillon for answering :)

**Closed by kaelig** 2017-02-17 18:51 UTC
Labels: status:duplicate

**Comment by ktevatt** [comment] 2017-02-21 15:29
Thank you both @kaelig and @FabienTaillon. Apologies for the dupe!
