### ISSUE TITLE
Lowercase 'e' styling issue

### ISSUE THREAD

**Issue by mikeh9summer** [salesforce-ux/design-system#448] opened 2017-05-08 12:13 UTC
Has anyone else notice the lower case 'e' looks like the bottom of it is cut off.  You can also see this in Lightning Experience.  Some look fine but others are not.
Wondering if there's a simple fix...

![lowercase_e_issue](https://cloud.githubusercontent.com/assets/28533198/25803652/e05fd346-33c5-11e7-8a2f-ea55427567b1.png)

**Comment by ishakasliwal** [comment] 2017-05-16 21:45
@mikeh9summer Thanks for pointing this out. We're looking into it!

**Comment by stefsullrew** [comment] 2017-05-26 17:13
@mikeh9summer - What browser are you using? It looks like IE and a possible anti-aliasing issue since the letters with descenders aren't cut off (like the g). 

I would try opening Chrome or FFOX to see if you see the same thing. If not, there's a setting in IE that you can turn on for smoothing. Since we can't reproduce, I'm going to close this. Cheers!

**Closed by stefsullrew** 2017-05-26 17:13 UTC
Labels: help wanted

**Comment by mikeh9summer** [comment] 2017-05-26 17:30
This is in chrome.  It seems to only be an issue with letters that switch from left to right which is the lower case 'e' and capital 'Q' although I can't really tell if it's happening on the 'Q'

![lowercase_e](https://cloud.githubusercontent.com/assets/28533198/26505554/43bb3b2e-4217-11e7-8811-a32098dfe4a7.png)

**Comment by daveespo** [comment] 2017-05-31 17:19
@stefsullrew we're seeing this on Microsoft Edge, Chrome and Firefox on Windows 10

Here's an example (magnified so it's easier to see)

https://www.screencast.com/t/JFTpkatp8Je
