### ISSUE TITLE
Focus Border on App Launcher Button is not centered

### ISSUE THREAD

**Issue by AllanOricil** [salesforce-ux/design-system#665] opened 2020-09-03 15:44 UTC
This is very perceived because when you click on the App Launcher it takes quite some time to do something. 

![image](https://user-images.githubusercontent.com/55927613/92136920-806b0a80-ee04-11ea-8392-216dc8e32291.png)
![image](https://user-images.githubusercontent.com/55927613/92137091-b0b2a900-ee04-11ea-8eb6-8aa5b1a956d6.png)

**Comment by kflournoy-sf** [comment] 2020-09-04 22:40
Hi @AllanOricil !

I am not seeing this behavior for that button in our [Global Navigation blueprint](https://lightningdesignsystem.com/components/global-navigation/#site-main-content). From the screenshot of your inspector, it seems that you are overriding the default SLDS styles in at least one way - per our [developer documentation](https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/lightning_base_slds.htm), we don't recommend overriding SLDS styles but instead creating your own separate class names and targeting those. (See "Applying Custom Component Styling" in the link above)

If you're able to reproduce this issue in our Blueprint on our website please let me know, but I believe that the issue is somewhere in your implementation of the pattern.

Please let me know if you have any further questions,
-Kim

**Comment by AllanOricil** [comment] 2020-09-05 12:17
> Hi @AllanOricil !
> 
> I am not seeing this behavior for that button in our [Global Navigation blueprint](https://lightningdesignsystem.com/components/global-navigation/#site-main-content), checked with multiple browsers.
> 
> From the screenshot of your inspector, it seems that you are overriding the default SLDS styles in at least one way - per our [developer documentation](https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/lightning_base_slds.htm), we don't recommend overriding SLDS styles but instead creating your own separate class names and targeting those. (See "Applying Custom Component Styling" in the link above)
> 
> If you're able to reproduce this issue in our Blueprint on our website please let me know, but I believe that the issue is somewhere in your implementation of the pattern.
> 
> Please let me know if you have any further questions,
> -Kim
> 
> <img alt="Screen Shot 2020-09-04 at 6 42 09 PM" width="1171" src="https://user-images.githubusercontent.com/53910308/92289412-630a6f00-eede-11ea-84d4-766256e9d449.png">

@kflournoy-sf  Im not overriding the styles. I took the screenshot from a Salesforce Sandbox and just added the focus to show to you that it has :focus styles.

**Comment by kflournoy-sf** [comment] 2020-09-09 19:22
@AllanOricil - ok, thank you for providing more information! I do see that issue in my sandbox org, and I'm not quite sure what's going on. Since it's not an SLDS issue I'm going to close this issue, but I will try and find the team internally who is responsible for that portion of the UI and file a ticket on them. Thank you so much for your feedback!

**Closed by kflournoy-sf** 2020-09-09 19:22 UTC
Labels: awaiting feedback
