### ISSUE TITLE
salesforce-ux/icons fatal: Could not read from remote repository

### ISSUE THREAD

**Issue by mdolzhko** [salesforce-ux/design-system#195] opened 2016-04-11 11:42 UTC
Hi everyone!
here is a description of bug after 'npm install'

please take a look at this issue:
it's related to https://github.com/salesforce-ux/design-system/issues/194 ticket too
[npm-debug.log.zip](https://github.com/salesforce-ux/design-system/files/212858/npm-debug.log.zip)

npm install @salesforce-ux/icons --save   
     
npm ERR! git clone git@github.com:salesforce-ux/icons Cloning into bare repository '/home/den/.npm/_git-remotes/git-github-com-salesforce-ux-icons-cf3f3171'...
npm ERR! git clone git@github.com:salesforce-ux/icons Warning: Permanently added the RSA host key for IP address '192.30.252.131' to the list of known hosts.
npm ERR! git clone git@github.com:salesforce-ux/icons Permission denied (publickey).
npm ERR! git clone git@github.com:salesforce-ux/icons fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:salesforce-ux/icons 
npm ERR! git clone git@github.com:salesforce-ux/icons Please make sure you have the correct access rights
npm ERR! git clone git@github.com:salesforce-ux/icons and the repository exists.

**Comment by kaelig** [comment] 2016-04-11 19:11
Hi @mdolzhko, thanks again for opening an issue on this.

Looks like something is going on with the npm configuration on your machine, and we can't seem to be able to reproduce that issue.

First of all, it's trying to install the module from the github repository instead of the npm registry, which is weird.

Is there an internal npm registry server/mirror/proxy that your machine is running or in your company?

**Comment by kaelig** [comment] 2016-05-18 20:59
This looks like a duplicate of #194, let's investigate over there.

**Closed by kaelig** 2016-05-18 20:59 UTC
