### ISSUE TITLE
npm install @salesforce-ux/design-system --save is not working 

### ISSUE THREAD

**Issue by ajayjoji** [salesforce-ux/design-system#538] opened 2018-03-18 10:57 UTC
npm install @salesforce-ux/design-system --save this command is giving below error. 

npm ERR! code E404
npm ERR! 404 Not Found: @salesforce-ux/design-system@latest

Node Version: v8.1.0
npm Version: 5.7.1

I have tried with latest node version as well but still the issue is occurring. Could some one please share me some hint. Detailed log is attached.

[2018-03-18T10_51_16_400Z-debug.log](https://github.com/salesforce-ux/design-system/files/1822597/2018-03-18T10_51_16_400Z-debug.log)

**Comment by engai** [comment] 2018-03-19 21:01
@ajayjoji Unfortunately, I was unable to reproduce your issue with Mac OSX Terminal and Windows 10 Powershell. 

What OS and command-line tool are you using to run the command?

**Comment by fspoettel** [comment] 2018-03-23 11:11
@ajayjoji The log indicates a `404` while fetching `https://registry.npmjs.org/@salesforce-ux%2fdesign-system`. The URL seems to work and the latest tag points to the correct version. This indicates a temporary hiccup when resolving the package, is this still happening for you?

**Comment by ajayjoji** [comment] 2018-03-24 05:27
Yes i am still facing the issue. Updated npm to 5.8.0
URL is accessible but throwing the same error once i run the command.

[2018-03-24T05_22_07_015Z-debug.log](https://github.com/salesforce-ux/design-system/files/1844050/2018-03-24T05_22_07_015Z-debug.log)

**Comment by fspoettel** [comment] 2018-03-24 10:41
Bummer. It would be great if you could try a few things in order to narrow this problem down:

* Please first reset the npm cache via `npm cache clean`
* If there is a `package-lock.json` in your folder, remove it
* Try installing again, does it work know?
* Can you install other packages that are pubished under a private namespace (e.g. `@storybook/cli`)?
* If you have `yarn` installed: Does a `yarn install` in the same project work?

It seems like the problem you are seeing is a bug with npm rather than this project.  There are multiple open npm issues that describe the behavior you are seeing, https://github.com/npm/registry/issues/272 https://github.com/npm/npm/issues/19254.

**Comment by ajayjoji** [comment] 2018-03-28 01:05
I switched to old npm version <5.0 and the it works. Thanks for the support @fspoettel  and @engai.
 If the npm is >= 5.0 then the same error was getting thrown for all the commands starting with @.

**Comment by engai** [comment] 2018-04-02 18:36
@ajayjoji glad you were able to resolve your issue. Closing this as it may not be an issue with our system, but rather with npm. Feel free to comment or reopen if needed!

@fspoettel thank you for the assist!

**Closed by engai** 2018-04-02 18:36 UTC
